# Generated by Django 3.2.6 on 2021-08-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthyrecipe',
            name='NumberRatings',
            field=models.CharField(default='good', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unhealthyrecipe',
            name='NumberRatings',
            field=models.CharField(default=112, max_length=50),
            preserve_default=False,
        ),
    ]
