# Generated by Django 3.2.6 on 2021-08-31 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0005_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendations',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
